# Generated by Django 5.1.2 on 2024-10-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canchas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('deporte', models.CharField(max_length=50)),
                ('reserva', models.BooleanField(default=False)),
            ],
        ),
    ]
