# Generated by Django 5.1.2 on 2024-11-02 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='myapp.canchas')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='myapp.horario')),
            ],
        ),
    ]
