# Generated by Django 5.1.2 on 2024-11-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_horario_hora_fin_remove_horario_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
    ]
