# Generated by Django 5.1.2 on 2024-11-21 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_horario_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersona2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='myapp.canchas')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='myapp.horario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DatosPersona',
        ),
    ]
